# !!! Make sure that you have already created a new project and your current working directory equals the project's directory.
# The project directory needs to contain all downloaded files
# Also make sure that your computer is connected to the internet while running the script because some functions connect to online databases.

# Install and load all required packages using the versions listed in the reproducing.lock file.
renv_installed <- require("renv")
if (renv_installed==FALSE){
  if (!requireNamespace("remotes")){
    install.packages("remotes")
  }
  remotes::install_github("rstudio/renv")
}

renv::init(project=NULL, bare = TRUE)
renv::restore(lockfile = "renv_20220310", prompt = FALSE)
.rs.restartR()


set.seed(1)
library(Seurat)
library(SingleCellExperiment)
library(AnnotationHub)
library(EnsDb.Mmusculus.v79)
library(scater)
library(rlist)
library(scran)
library(tidyr)
library(dplyr)
library(destiny)
library(igraph)
library(cluster)
library(ggplot2)
library(patchwork)
library(SingleR)
library(tibble)
library(scDblFinder)
library(slingshot)
library(grDevices)
library(GiNA)
library(gridExtra)
library(plotly)
library(EDASeq)
library(slider)
library(FateID)
library(pheatmap)
library(ggpubr)
library(grDevices)
library(rgl)
library(magick)
library(maptree)

# load required functions
source("script2.R", local=FALSE)

# specifiy paths to the filtered count matrices which were generated by the CellRanger pipeline (version 3.1.0; transcriptome mm10-3.0.0; chemistry Single Cell 3' v3)
path_HSC_WT <- "/Volumes/addition_storage/U22WT1_HSC/filtered_feature_bc_matrix/"
path_HSC_KO <- "/Volumes/addition_storage/U22cKO1_HSC/filtered_feature_bc_matrix/"
path_ST_WT <- "/Volumes/addition_storage/U22WT1_ST/filtered_feature_bc_matrix/"
path_ST_KO <- "/Volumes/addition_storage/U22cKO1_ST/filtered_feature_bc_matrix/"
path_MPP_WT <- "/Volumes/addition_storage/U22WT1_MPP/filtered_feature_bc_matrix/"
path_MPP_KO <- "/Volumes/addition_storage/U22cKO1_MPP/filtered_feature_bc_matrix/"
path_LSK_WT <- "/Volumes/addition_storage/U22WT1_LSK/filtered_feature_bc_matrix/"
path_LSK_KO <- "/Volumes/addition_storage/U22cKO1_LSK/filtered_feature_bc_matrix/"
path_Linminus_WT <- "/Volumes/addition_storage/U22WT1_Linminus/filtered_feature_bc_matrix/"
path_Linminus_KO <- "/Volumes/addition_storage/U22cKO1_Linminus/filtered_feature_bc_matrix/"
path_TBM_WT <- "/Volumes/addition_storage/U22WT1_TBM/filtered_feature_bc_matrix/"
path_TBM_KO <- "/Volumes/addition_storage/U22cKO1_TBM/filtered_feature_bc_matrix/"

# create folder into which all plots will be saved
path_to_working_directory <- getwd()
folder_with_plots <- "test_plots_20220313"
dir.create(paste(path_to_working_directory, folder_with_plots, sep="/"), showWarnings = FALSE)

# analysis of total bone marrow
source("analysis_of_total_bone_marrow.R", local=FALSE)

# analysis of MPPs and HSCs
source("analysis_of_MPPs_and_HSCs.R", local=FALSE)

