# !!! Make sure to follow the instructions in the README file

# Install and load all required packages using the versions listed in the reproducing.lock file.
renv_installed <- require("renv")
if (renv_installed==FALSE){
  if (!requireNamespace("remotes")){
    install.packages("remotes")
  }
  remotes::install_github("rstudio/renv")
}

renv::init(project=NULL, bare = TRUE)
renv::restore(lockfile = "renv_20220310", prompt = FALSE)
.rs.restartR()


set.seed(1)
library(Seurat)
library(SingleCellExperiment)
library(AnnotationHub)
library(EnsDb.Mmusculus.v79)
library(scater)
library(rlist)
library(scran)
library(tidyr)
library(dplyr)
library(destiny)
library(igraph)
library(cluster)
library(ggplot2)
library(patchwork)
library(SingleR)
library(tibble)
library(scDblFinder)
library(slingshot)
library(grDevices)
library(GiNA)
library(gridExtra)
library(plotly)
library(EDASeq)
library(slider)
library(FateID)
library(pheatmap)
library(ggpubr)
library(grDevices)
library(rgl)
library(magick)
library(maptree)

# load required functions
source("script2.R", local=FALSE)

# specify on which replicate the pipeline will be run (1 or 2)
replicate <- 1

# specify whether intermediate results should be saved
save_intermediate_results <- FALSE

# specify whether final objects containing processed cell data should be saved
save_final_objects <- FALSE

# specify whether saved objects containing intermediate results from a previous run should be loaded to quickly reproduce plots
load_intermediate_results <- TRUE

# if needed, specify paths of objects with intermediate results
if ((load_intermediate_results == TRUE) | (save_intermediate_results == TRUE) | (save_final_objects == TRUE)){
  paths_of_objects <- get_paths_for_intermediate_results(replicate_ID = replicate, 
                                                         paths_to_results="/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/R_objects_Usp22/objects_with_intermediate_results/", 
                                                         prefixMPPs="MPPs_after_annotation", 
                                                         prefixTBM="TBM_after_annotation",
                                                         prefixHSC="LT_ST_after_merge")
}

# load replicate-specific parameters (e.g. different filter thresholds in initial quality control)
replicate_parameters <- load_replicate_parameters(replicate=replicate)

# specifiy paths to the filtered count matrices which were generated by the CellRanger pipeline (version 3.1.0; transcriptome mm10-3.0.0; chemistry Single Cell 3' v3)
if (replicate==1){
  path_HSC_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22WT1_HSC/filtered_feature_bc_matrix/"
  path_HSC_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22cKO1_HSC/filtered_feature_bc_matrix/"
  path_ST_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22WT1_ST/filtered_feature_bc_matrix/"
  path_ST_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22cKO1_ST/filtered_feature_bc_matrix/"
  path_MPP_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22WT1_MPP/filtered_feature_bc_matrix/"
  path_MPP_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22cKO1_MPP/filtered_feature_bc_matrix/"
  path_TBM_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22WT1_TBM/filtered_feature_bc_matrix/"
  path_TBM_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/first_data_Niko/U22cKO1_TBM/filtered_feature_bc_matrix/"
}
if (replicate==2){
  path_HSC_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/WT1LTHSC/filtered_feature_bc_matrix/"
  path_HSC_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/KO1LTHSC/filtered_feature_bc_matrix/"
  path_ST_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/WT1STHSC/filtered_feature_bc_matrix/"
  path_ST_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/KO1STHSC/filtered_feature_bc_matrix/"
  path_MPP_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/WT1MPP/filtered_feature_bc_matrix/"
  path_MPP_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/KO1MPP/filtered_feature_bc_matrix/"
  path_TBM_WT <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/WT1TBM/filtered_feature_bc_matrix/"
  path_TBM_KO <- "/Users/metz/Nextcloud/backup_Usp22_data_and_Robjects/revision_data_Niko/KO1TBM/filtered_feature_bc_matrix/"
}

# create folder into which all plots will be saved
path_to_working_directory <- getwd()
folder_with_plots <- paste("test_20220817", as.character(replicate_parameters[["replicate"]]), sep = "_")
dir.create(paste(path_to_working_directory, folder_with_plots, sep="/"), showWarnings = FALSE)

# analysis of total bone marrow
source("analysis_of_total_bone_marrow.R", local=FALSE)


# analysis of MPPs and HSCs
source("analysis_of_MPPs_and_HSCs.R", local=FALSE)

